version: '3'

services:
  api:
    container_name: api # Name can be anything
    restart: always
    build: ./flask_app
    ports:
      - "5000:5000"
    # command: gunicorn -w 1 -b :8080 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    expose:
      - "8080"
    ports:
      - "80:8080"
    depends_on:
      - api